name: Wakatime Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: dvjn/wakatime-charts@master
        with:
          WAKATIME_API_KEY: 87c2116c-255a-4253-899b-c88017f80d6e
